---
abstract: 'Change ticket metadata via email'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  IPC::Open2: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-CommandByMail
no_index:
  directory:
    - etc
    - inc
    - xt
  package:
    - RT::Extension::CommandByMail::Test
    - RT::Extension::CommandByMail::Test
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-commandbymail
version: '3.00'
x_module_install_rtx_version: '0.38'
x_requires_rt: 4.0.0
