abstract: RT Extension-CommandByMail Extension
author: Jesse Vincent <jesse@bestpractical.com>
build_requires: 
  IPC::Open2: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: RT-Extension-CommandByMail
no_index: 
  directory: 
    - inc
    - t
requires: 
  MIME::Entity: 5.420
  UNIVERSAL::require: 0
version: 0.03
